[tool.black]
line-length = 120
target-version = ['py39']
include = '\.pyi?$'
extend-exclude = '''
# A regex preceded with ^/ will apply only to files and directories
# in the root of the project.
^/migrations/
'''

[tool.isort]
profile = "black"
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
ensure_newline_before_comments = true
line_length = 120
skip = ["migrations", ".git", "__pycache__", "docs", ".env", "venv", ".venv"]
skip_glob = ["*/migrations/*.py"]
sections = ["FUTURE", "STDLIB", "THIRDPARTY", "DJANGO", "DJANGOTHIRDPARTY", "FIRSTPARTY", "LOCALFOLDER"]
known_django = ["django"]
known_djangothirdparty = ["rest_framework", "django_filters", "drf_yasg", "django_prometheus"]
